(in-package #:advent2015)

(defun read-floor-instructions ()
  (uiop:read-file-string (asdf:system-relative-pathname 'advent2015
                                                        "inputs/day1")))

(defun day1/solution1 ()
  (let ((floor 0))
    (loop for c across (read-floor-instructions)
          if (char-equal c #\()
            do (incf floor)
          if (char-equal c #\))
            do (decf floor)
          finally (return floor))))

(defun day1/solution2 ()
  (let ((floor 0)
        (pos 1))
    (loop for c across (read-floor-instructions)
          if (char-equal c #\()
            do (incf floor)
               (incf pos)
          if (char-equal c #\))
            do (decf floor)
               (incf pos)
          until (= floor -1)
          finally (return (- pos 1)))))
